version: '3.4'
services:
  api:
    extends:
      service: api
      file: docker-compose.override.yml

  redis:
    extends:
      service: redis
      file: docker-compose.override.yml

  elasticsearch:
    extends:
      service: elasticsearch
      file: docker-compose.override.yml


  tests:
    image: async_api_image

    entrypoint: > 
      sh -c "pip install -r tests/functional/requirements.txt
      && python3 tests/functional/utils/wait_for_es.py
      && python3 tests/functional/utils/wait_for_redis.py"
      && pytest tests/functional/src"
